/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HemocentroIndexRouteImport } from './routes/hemocentro.index'
import { Route as HemocentroIndicadoresRouteImport } from './routes/hemocentro.indicadores'
import { Route as HospitalIndexRouteImport } from './routes/hospital.index'
import { Route as HospitalNovaSolicitacaoRouteImport } from './routes/hospital.nova-solicitacao'
import { Route as HemocentroDistribuicoesIndexRouteImport } from './routes/hemocentro.distribuicoes.index'
import { Route as HemocentroDistribuicoesIdRouteImport } from './routes/hemocentro.distribuicoes.$id'
import { Route as HemocentroDistribuicoesPlanejarRouteImport } from './routes/hemocentro.distribuicoes.planejar'
import { Route as HemocentroEstoqueIndexRouteImport } from './routes/hemocentro.estoque.index'
import { Route as HemocentroEstoqueNovoRouteImport } from './routes/hemocentro.estoque.novo'
import { Route as HemocentroSolicitacoesIndexRouteImport } from './routes/hemocentro.solicitacoes.index'
import { Route as HemocentroSolicitacoesIdRouteImport } from './routes/hemocentro.solicitacoes.$id'
import { Route as HospitalSolicitacoesIndexRouteImport } from './routes/hospital.solicitacoes.index'
import { Route as HospitalSolicitacoesIdRouteImport } from './routes/hospital.solicitacoes.$id'
import { Route as HospitalTransportesIndexRouteImport } from './routes/hospital.transportes.index'
import { Route as HospitalTransportesIdRouteImport } from './routes/hospital.transportes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HemocentroIndexRoute = HemocentroIndexRouteImport.update({
  id: '/hemocentro/',
  path: '/hemocentro/',
  getParentRoute: () => rootRouteImport,
} as any)
const HemocentroIndicadoresRoute = HemocentroIndicadoresRouteImport.update({
  id: '/hemocentro/indicadores',
  path: '/hemocentro/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalIndexRoute = HospitalIndexRouteImport.update({
  id: '/hospital/',
  path: '/hospital/',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalNovaSolicitacaoRoute = HospitalNovaSolicitacaoRouteImport.update({
  id: '/hospital/nova-solicitacao',
  path: '/hospital/nova-solicitacao',
  getParentRoute: () => rootRouteImport,
} as any)
const HemocentroDistribuicoesIndexRoute =
  HemocentroDistribuicoesIndexRouteImport.update({
    id: '/hemocentro/distribuicoes/',
    path: '/hemocentro/distribuicoes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const HemocentroDistribuicoesIdRoute =
  HemocentroDistribuicoesIdRouteImport.update({
    id: '/hemocentro/distribuicoes/$id',
    path: '/hemocentro/distribuicoes/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const HemocentroDistribuicoesPlanejarRoute =
  HemocentroDistribuicoesPlanejarRouteImport.update({
    id: '/hemocentro/distribuicoes/planejar',
    path: '/hemocentro/distribuicoes/planejar',
    getParentRoute: () => rootRouteImport,
  } as any)
const HemocentroEstoqueIndexRoute = HemocentroEstoqueIndexRouteImport.update({
  id: '/hemocentro/estoque/',
  path: '/hemocentro/estoque/',
  getParentRoute: () => rootRouteImport,
} as any)
const HemocentroEstoqueNovoRoute = HemocentroEstoqueNovoRouteImport.update({
  id: '/hemocentro/estoque/novo',
  path: '/hemocentro/estoque/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const HemocentroSolicitacoesIndexRoute =
  HemocentroSolicitacoesIndexRouteImport.update({
    id: '/hemocentro/solicitacoes/',
    path: '/hemocentro/solicitacoes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const HemocentroSolicitacoesIdRoute =
  HemocentroSolicitacoesIdRouteImport.update({
    id: '/hemocentro/solicitacoes/$id',
    path: '/hemocentro/solicitacoes/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const HospitalSolicitacoesIndexRoute =
  HospitalSolicitacoesIndexRouteImport.update({
    id: '/hospital/solicitacoes/',
    path: '/hospital/solicitacoes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const HospitalSolicitacoesIdRoute = HospitalSolicitacoesIdRouteImport.update({
  id: '/hospital/solicitacoes/$id',
  path: '/hospital/solicitacoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalTransportesIndexRoute =
  HospitalTransportesIndexRouteImport.update({
    id: '/hospital/transportes/',
    path: '/hospital/transportes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const HospitalTransportesIdRoute = HospitalTransportesIdRouteImport.update({
  id: '/hospital/transportes/$id',
  path: '/hospital/transportes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/hemocentro/indicadores': typeof HemocentroIndicadoresRoute
  '/hospital/nova-solicitacao': typeof HospitalNovaSolicitacaoRoute
  '/hemocentro/': typeof HemocentroIndexRoute
  '/hospital/': typeof HospitalIndexRoute
  '/hemocentro/distribuicoes/$id': typeof HemocentroDistribuicoesIdRoute
  '/hemocentro/distribuicoes/planejar': typeof HemocentroDistribuicoesPlanejarRoute
  '/hemocentro/estoque/novo': typeof HemocentroEstoqueNovoRoute
  '/hemocentro/solicitacoes/$id': typeof HemocentroSolicitacoesIdRoute
  '/hospital/solicitacoes/$id': typeof HospitalSolicitacoesIdRoute
  '/hospital/transportes/$id': typeof HospitalTransportesIdRoute
  '/hemocentro/distribuicoes/': typeof HemocentroDistribuicoesIndexRoute
  '/hemocentro/estoque/': typeof HemocentroEstoqueIndexRoute
  '/hemocentro/solicitacoes/': typeof HemocentroSolicitacoesIndexRoute
  '/hospital/solicitacoes/': typeof HospitalSolicitacoesIndexRoute
  '/hospital/transportes/': typeof HospitalTransportesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/hemocentro/indicadores': typeof HemocentroIndicadoresRoute
  '/hospital/nova-solicitacao': typeof HospitalNovaSolicitacaoRoute
  '/hemocentro': typeof HemocentroIndexRoute
  '/hospital': typeof HospitalIndexRoute
  '/hemocentro/distribuicoes/$id': typeof HemocentroDistribuicoesIdRoute
  '/hemocentro/distribuicoes/planejar': typeof HemocentroDistribuicoesPlanejarRoute
  '/hemocentro/estoque/novo': typeof HemocentroEstoqueNovoRoute
  '/hemocentro/solicitacoes/$id': typeof HemocentroSolicitacoesIdRoute
  '/hospital/solicitacoes/$id': typeof HospitalSolicitacoesIdRoute
  '/hospital/transportes/$id': typeof HospitalTransportesIdRoute
  '/hemocentro/distribuicoes': typeof HemocentroDistribuicoesIndexRoute
  '/hemocentro/estoque': typeof HemocentroEstoqueIndexRoute
  '/hemocentro/solicitacoes': typeof HemocentroSolicitacoesIndexRoute
  '/hospital/solicitacoes': typeof HospitalSolicitacoesIndexRoute
  '/hospital/transportes': typeof HospitalTransportesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/hemocentro/indicadores': typeof HemocentroIndicadoresRoute
  '/hospital/nova-solicitacao': typeof HospitalNovaSolicitacaoRoute
  '/hemocentro/': typeof HemocentroIndexRoute
  '/hospital/': typeof HospitalIndexRoute
  '/hemocentro/distribuicoes/$id': typeof HemocentroDistribuicoesIdRoute
  '/hemocentro/distribuicoes/planejar': typeof HemocentroDistribuicoesPlanejarRoute
  '/hemocentro/estoque/novo': typeof HemocentroEstoqueNovoRoute
  '/hemocentro/solicitacoes/$id': typeof HemocentroSolicitacoesIdRoute
  '/hospital/solicitacoes/$id': typeof HospitalSolicitacoesIdRoute
  '/hospital/transportes/$id': typeof HospitalTransportesIdRoute
  '/hemocentro/distribuicoes/': typeof HemocentroDistribuicoesIndexRoute
  '/hemocentro/estoque/': typeof HemocentroEstoqueIndexRoute
  '/hemocentro/solicitacoes/': typeof HemocentroSolicitacoesIndexRoute
  '/hospital/solicitacoes/': typeof HospitalSolicitacoesIndexRoute
  '/hospital/transportes/': typeof HospitalTransportesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/hemocentro/indicadores'
    | '/hospital/nova-solicitacao'
    | '/hemocentro/'
    | '/hospital/'
    | '/hemocentro/distribuicoes/$id'
    | '/hemocentro/distribuicoes/planejar'
    | '/hemocentro/estoque/novo'
    | '/hemocentro/solicitacoes/$id'
    | '/hospital/solicitacoes/$id'
    | '/hospital/transportes/$id'
    | '/hemocentro/distribuicoes/'
    | '/hemocentro/estoque/'
    | '/hemocentro/solicitacoes/'
    | '/hospital/solicitacoes/'
    | '/hospital/transportes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/hemocentro/indicadores'
    | '/hospital/nova-solicitacao'
    | '/hemocentro'
    | '/hospital'
    | '/hemocentro/distribuicoes/$id'
    | '/hemocentro/distribuicoes/planejar'
    | '/hemocentro/estoque/novo'
    | '/hemocentro/solicitacoes/$id'
    | '/hospital/solicitacoes/$id'
    | '/hospital/transportes/$id'
    | '/hemocentro/distribuicoes'
    | '/hemocentro/estoque'
    | '/hemocentro/solicitacoes'
    | '/hospital/solicitacoes'
    | '/hospital/transportes'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/login'
    | '/hemocentro/indicadores'
    | '/hospital/nova-solicitacao'
    | '/hemocentro/'
    | '/hospital/'
    | '/hemocentro/distribuicoes/$id'
    | '/hemocentro/distribuicoes/planejar'
    | '/hemocentro/estoque/novo'
    | '/hemocentro/solicitacoes/$id'
    | '/hospital/solicitacoes/$id'
    | '/hospital/transportes/$id'
    | '/hemocentro/distribuicoes/'
    | '/hemocentro/estoque/'
    | '/hemocentro/solicitacoes/'
    | '/hospital/solicitacoes/'
    | '/hospital/transportes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  HemocentroIndicadoresRoute: typeof HemocentroIndicadoresRoute
  HospitalNovaSolicitacaoRoute: typeof HospitalNovaSolicitacaoRoute
  HemocentroIndexRoute: typeof HemocentroIndexRoute
  HospitalIndexRoute: typeof HospitalIndexRoute
  HemocentroDistribuicoesIdRoute: typeof HemocentroDistribuicoesIdRoute
  HemocentroDistribuicoesPlanejarRoute: typeof HemocentroDistribuicoesPlanejarRoute
  HemocentroEstoqueNovoRoute: typeof HemocentroEstoqueNovoRoute
  HemocentroSolicitacoesIdRoute: typeof HemocentroSolicitacoesIdRoute
  HospitalSolicitacoesIdRoute: typeof HospitalSolicitacoesIdRoute
  HospitalTransportesIdRoute: typeof HospitalTransportesIdRoute
  HemocentroDistribuicoesIndexRoute: typeof HemocentroDistribuicoesIndexRoute
  HemocentroEstoqueIndexRoute: typeof HemocentroEstoqueIndexRoute
  HemocentroSolicitacoesIndexRoute: typeof HemocentroSolicitacoesIndexRoute
  HospitalSolicitacoesIndexRoute: typeof HospitalSolicitacoesIndexRoute
  HospitalTransportesIndexRoute: typeof HospitalTransportesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hemocentro/': {
      id: '/hemocentro/'
      path: '/hemocentro'
      fullPath: '/hemocentro/'
      preLoaderRoute: typeof HemocentroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hemocentro/indicadores': {
      id: '/hemocentro/indicadores'
      path: '/hemocentro/indicadores'
      fullPath: '/hemocentro/indicadores'
      preLoaderRoute: typeof HemocentroIndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/': {
      id: '/hospital/'
      path: '/hospital'
      fullPath: '/hospital/'
      preLoaderRoute: typeof HospitalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/nova-solicitacao': {
      id: '/hospital/nova-solicitacao'
      path: '/hospital/nova-solicitacao'
      fullPath: '/hospital/nova-solicitacao'
      preLoaderRoute: typeof HospitalNovaSolicitacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hemocentro/distribuicoes/': {
      id: '/hemocentro/distribuicoes/'
      path: '/hemocentro/distribuicoes'
      fullPath: '/hemocentro/distribuicoes/'
      preLoaderRoute: typeof HemocentroDistribuicoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hemocentro/distribuicoes/$id': {
      id: '/hemocentro/distribuicoes/$id'
      path: '/hemocentro/distribuicoes/$id'
      fullPath: '/hemocentro/distribuicoes/$id'
      preLoaderRoute: typeof HemocentroDistribuicoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hemocentro/distribuicoes/planejar': {
      id: '/hemocentro/distribuicoes/planejar'
      path: '/hemocentro/distribuicoes/planejar'
      fullPath: '/hemocentro/distribuicoes/planejar'
      preLoaderRoute: typeof HemocentroDistribuicoesPlanejarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hemocentro/estoque/': {
      id: '/hemocentro/estoque/'
      path: '/hemocentro/estoque'
      fullPath: '/hemocentro/estoque/'
      preLoaderRoute: typeof HemocentroEstoqueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hemocentro/estoque/novo': {
      id: '/hemocentro/estoque/novo'
      path: '/hemocentro/estoque/novo'
      fullPath: '/hemocentro/estoque/novo'
      preLoaderRoute: typeof HemocentroEstoqueNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hemocentro/solicitacoes/': {
      id: '/hemocentro/solicitacoes/'
      path: '/hemocentro/solicitacoes'
      fullPath: '/hemocentro/solicitacoes/'
      preLoaderRoute: typeof HemocentroSolicitacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hemocentro/solicitacoes/$id': {
      id: '/hemocentro/solicitacoes/$id'
      path: '/hemocentro/solicitacoes/$id'
      fullPath: '/hemocentro/solicitacoes/$id'
      preLoaderRoute: typeof HemocentroSolicitacoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/solicitacoes/': {
      id: '/hospital/solicitacoes/'
      path: '/hospital/solicitacoes'
      fullPath: '/hospital/solicitacoes/'
      preLoaderRoute: typeof HospitalSolicitacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/solicitacoes/$id': {
      id: '/hospital/solicitacoes/$id'
      path: '/hospital/solicitacoes/$id'
      fullPath: '/hospital/solicitacoes/$id'
      preLoaderRoute: typeof HospitalSolicitacoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/transportes/': {
      id: '/hospital/transportes/'
      path: '/hospital/transportes'
      fullPath: '/hospital/transportes/'
      preLoaderRoute: typeof HospitalTransportesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/transportes/$id': {
      id: '/hospital/transportes/$id'
      path: '/hospital/transportes/$id'
      fullPath: '/hospital/transportes/$id'
      preLoaderRoute: typeof HospitalTransportesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  HemocentroIndicadoresRoute: HemocentroIndicadoresRoute,
  HospitalNovaSolicitacaoRoute: HospitalNovaSolicitacaoRoute,
  HemocentroIndexRoute: HemocentroIndexRoute,
  HospitalIndexRoute: HospitalIndexRoute,
  HemocentroDistribuicoesIdRoute: HemocentroDistribuicoesIdRoute,
  HemocentroDistribuicoesPlanejarRoute: HemocentroDistribuicoesPlanejarRoute,
  HemocentroEstoqueNovoRoute: HemocentroEstoqueNovoRoute,
  HemocentroSolicitacoesIdRoute: HemocentroSolicitacoesIdRoute,
  HospitalSolicitacoesIdRoute: HospitalSolicitacoesIdRoute,
  HospitalTransportesIdRoute: HospitalTransportesIdRoute,
  HemocentroDistribuicoesIndexRoute: HemocentroDistribuicoesIndexRoute,
  HemocentroEstoqueIndexRoute: HemocentroEstoqueIndexRoute,
  HemocentroSolicitacoesIndexRoute: HemocentroSolicitacoesIndexRoute,
  HospitalSolicitacoesIndexRoute: HospitalSolicitacoesIndexRoute,
  HospitalTransportesIndexRoute: HospitalTransportesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
