/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AguardandoAprovacaoRouteImport } from './routes/aguardando-aprovacao'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as HemocentroRouteImport } from './routes/hemocentro'
import { Route as HospitalRouteImport } from './routes/hospital'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HemocentroIndexRouteImport } from './routes/hemocentro.index'
import { Route as HemocentroIndicadoresRouteImport } from './routes/hemocentro.indicadores'
import { Route as HospitalIndexRouteImport } from './routes/hospital.index'
import { Route as HospitalNovaSolicitacaoRouteImport } from './routes/hospital.nova-solicitacao'
import { Route as HemocentroDistribuicoesIndexRouteImport } from './routes/hemocentro.distribuicoes.index'
import { Route as HemocentroDistribuicoesIdRouteImport } from './routes/hemocentro.distribuicoes.$id'
import { Route as HemocentroDistribuicoesPlanejarRouteImport } from './routes/hemocentro.distribuicoes.planejar'
import { Route as HemocentroEstoqueIndexRouteImport } from './routes/hemocentro.estoque.index'
import { Route as HemocentroEstoqueNovoRouteImport } from './routes/hemocentro.estoque.novo'
import { Route as HemocentroSolicitacoesIndexRouteImport } from './routes/hemocentro.solicitacoes.index'
import { Route as HemocentroSolicitacoesIdRouteImport } from './routes/hemocentro.solicitacoes.$id'
import { Route as HospitalSolicitacoesIndexRouteImport } from './routes/hospital.solicitacoes.index'
import { Route as HospitalSolicitacoesIdRouteImport } from './routes/hospital.solicitacoes.$id'
import { Route as HospitalTransportesIndexRouteImport } from './routes/hospital.transportes.index'
import { Route as HospitalTransportesIdRouteImport } from './routes/hospital.transportes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AguardandoAprovacaoRoute = AguardandoAprovacaoRouteImport.update({
  id: '/aguardando-aprovacao',
  path: '/aguardando-aprovacao',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const HemocentroRoute = HemocentroRouteImport.update({
  id: '/hemocentro',
  path: '/hemocentro',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalRoute = HospitalRouteImport.update({
  id: '/hospital',
  path: '/hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HemocentroIndexRoute = HemocentroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HemocentroRoute,
} as any)
const HemocentroIndicadoresRoute = HemocentroIndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => HemocentroRoute,
} as any)
const HospitalIndexRoute = HospitalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalNovaSolicitacaoRoute = HospitalNovaSolicitacaoRouteImport.update({
  id: '/nova-solicitacao',
  path: '/nova-solicitacao',
  getParentRoute: () => HospitalRoute,
} as any)
const HemocentroDistribuicoesIndexRoute =
  HemocentroDistribuicoesIndexRouteImport.update({
    id: '/distribuicoes/',
    path: '/distribuicoes/',
    getParentRoute: () => HemocentroRoute,
  } as any)
const HemocentroDistribuicoesIdRoute =
  HemocentroDistribuicoesIdRouteImport.update({
    id: '/distribuicoes/$id',
    path: '/distribuicoes/$id',
    getParentRoute: () => HemocentroRoute,
  } as any)
const HemocentroDistribuicoesPlanejarRoute =
  HemocentroDistribuicoesPlanejarRouteImport.update({
    id: '/distribuicoes/planejar',
    path: '/distribuicoes/planejar',
    getParentRoute: () => HemocentroRoute,
  } as any)
const HemocentroEstoqueIndexRoute = HemocentroEstoqueIndexRouteImport.update({
  id: '/estoque/',
  path: '/estoque/',
  getParentRoute: () => HemocentroRoute,
} as any)
const HemocentroEstoqueNovoRoute = HemocentroEstoqueNovoRouteImport.update({
  id: '/estoque/novo',
  path: '/estoque/novo',
  getParentRoute: () => HemocentroRoute,
} as any)
const HemocentroSolicitacoesIndexRoute =
  HemocentroSolicitacoesIndexRouteImport.update({
    id: '/solicitacoes/',
    path: '/solicitacoes/',
    getParentRoute: () => HemocentroRoute,
  } as any)
const HemocentroSolicitacoesIdRoute =
  HemocentroSolicitacoesIdRouteImport.update({
    id: '/solicitacoes/$id',
    path: '/solicitacoes/$id',
    getParentRoute: () => HemocentroRoute,
  } as any)
const HospitalSolicitacoesIndexRoute =
  HospitalSolicitacoesIndexRouteImport.update({
    id: '/solicitacoes/',
    path: '/solicitacoes/',
    getParentRoute: () => HospitalRoute,
  } as any)
const HospitalSolicitacoesIdRoute = HospitalSolicitacoesIdRouteImport.update({
  id: '/solicitacoes/$id',
  path: '/solicitacoes/$id',
  getParentRoute: () => HospitalRoute,
} as any)
const HospitalTransportesIndexRoute =
  HospitalTransportesIndexRouteImport.update({
    id: '/transportes/',
    path: '/transportes/',
    getParentRoute: () => HospitalRoute,
  } as any)
const HospitalTransportesIdRoute = HospitalTransportesIdRouteImport.update({
  id: '/transportes/$id',
  path: '/transportes/$id',
  getParentRoute: () => HospitalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/cadastro': typeof CadastroRoute
  '/hemocentro': typeof HemocentroRouteWithChildren
  '/hospital': typeof HospitalRouteWithChildren
  '/login': typeof LoginRoute
  '/hemocentro/indicadores': typeof HemocentroIndicadoresRoute
  '/hospital/nova-solicitacao': typeof HospitalNovaSolicitacaoRoute
  '/hemocentro/': typeof HemocentroIndexRoute
  '/hospital/': typeof HospitalIndexRoute
  '/hemocentro/distribuicoes/$id': typeof HemocentroDistribuicoesIdRoute
  '/hemocentro/distribuicoes/planejar': typeof HemocentroDistribuicoesPlanejarRoute
  '/hemocentro/estoque/novo': typeof HemocentroEstoqueNovoRoute
  '/hemocentro/solicitacoes/$id': typeof HemocentroSolicitacoesIdRoute
  '/hospital/solicitacoes/$id': typeof HospitalSolicitacoesIdRoute
  '/hospital/transportes/$id': typeof HospitalTransportesIdRoute
  '/hemocentro/distribuicoes/': typeof HemocentroDistribuicoesIndexRoute
  '/hemocentro/estoque/': typeof HemocentroEstoqueIndexRoute
  '/hemocentro/solicitacoes/': typeof HemocentroSolicitacoesIndexRoute
  '/hospital/solicitacoes/': typeof HospitalSolicitacoesIndexRoute
  '/hospital/transportes/': typeof HospitalTransportesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/hemocentro/indicadores': typeof HemocentroIndicadoresRoute
  '/hospital/nova-solicitacao': typeof HospitalNovaSolicitacaoRoute
  '/hemocentro': typeof HemocentroIndexRoute
  '/hospital': typeof HospitalIndexRoute
  '/hemocentro/distribuicoes/$id': typeof HemocentroDistribuicoesIdRoute
  '/hemocentro/distribuicoes/planejar': typeof HemocentroDistribuicoesPlanejarRoute
  '/hemocentro/estoque/novo': typeof HemocentroEstoqueNovoRoute
  '/hemocentro/solicitacoes/$id': typeof HemocentroSolicitacoesIdRoute
  '/hospital/solicitacoes/$id': typeof HospitalSolicitacoesIdRoute
  '/hospital/transportes/$id': typeof HospitalTransportesIdRoute
  '/hemocentro/distribuicoes': typeof HemocentroDistribuicoesIndexRoute
  '/hemocentro/estoque': typeof HemocentroEstoqueIndexRoute
  '/hemocentro/solicitacoes': typeof HemocentroSolicitacoesIndexRoute
  '/hospital/solicitacoes': typeof HospitalSolicitacoesIndexRoute
  '/hospital/transportes': typeof HospitalTransportesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/cadastro': typeof CadastroRoute
  '/hemocentro': typeof HemocentroRouteWithChildren
  '/hospital': typeof HospitalRouteWithChildren
  '/login': typeof LoginRoute
  '/hemocentro/indicadores': typeof HemocentroIndicadoresRoute
  '/hospital/nova-solicitacao': typeof HospitalNovaSolicitacaoRoute
  '/hemocentro/': typeof HemocentroIndexRoute
  '/hospital/': typeof HospitalIndexRoute
  '/hemocentro/distribuicoes/$id': typeof HemocentroDistribuicoesIdRoute
  '/hemocentro/distribuicoes/planejar': typeof HemocentroDistribuicoesPlanejarRoute
  '/hemocentro/estoque/novo': typeof HemocentroEstoqueNovoRoute
  '/hemocentro/solicitacoes/$id': typeof HemocentroSolicitacoesIdRoute
  '/hospital/solicitacoes/$id': typeof HospitalSolicitacoesIdRoute
  '/hospital/transportes/$id': typeof HospitalTransportesIdRoute
  '/hemocentro/distribuicoes/': typeof HemocentroDistribuicoesIndexRoute
  '/hemocentro/estoque/': typeof HemocentroEstoqueIndexRoute
  '/hemocentro/solicitacoes/': typeof HemocentroSolicitacoesIndexRoute
  '/hospital/solicitacoes/': typeof HospitalSolicitacoesIndexRoute
  '/hospital/transportes/': typeof HospitalTransportesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aguardando-aprovacao'
    | '/cadastro'
    | '/hemocentro'
    | '/hospital'
    | '/login'
    | '/hemocentro/indicadores'
    | '/hospital/nova-solicitacao'
    | '/hemocentro/'
    | '/hospital/'
    | '/hemocentro/distribuicoes/$id'
    | '/hemocentro/distribuicoes/planejar'
    | '/hemocentro/estoque/novo'
    | '/hemocentro/solicitacoes/$id'
    | '/hospital/solicitacoes/$id'
    | '/hospital/transportes/$id'
    | '/hemocentro/distribuicoes/'
    | '/hemocentro/estoque/'
    | '/hemocentro/solicitacoes/'
    | '/hospital/solicitacoes/'
    | '/hospital/transportes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aguardando-aprovacao'
    | '/cadastro'
    | '/login'
    | '/hemocentro/indicadores'
    | '/hospital/nova-solicitacao'
    | '/hemocentro'
    | '/hospital'
    | '/hemocentro/distribuicoes/$id'
    | '/hemocentro/distribuicoes/planejar'
    | '/hemocentro/estoque/novo'
    | '/hemocentro/solicitacoes/$id'
    | '/hospital/solicitacoes/$id'
    | '/hospital/transportes/$id'
    | '/hemocentro/distribuicoes'
    | '/hemocentro/estoque'
    | '/hemocentro/solicitacoes'
    | '/hospital/solicitacoes'
    | '/hospital/transportes'
  id:
    | '__root__'
    | '/'
    | '/aguardando-aprovacao'
    | '/cadastro'
    | '/hemocentro'
    | '/hospital'
    | '/login'
    | '/hemocentro/indicadores'
    | '/hospital/nova-solicitacao'
    | '/hemocentro/'
    | '/hospital/'
    | '/hemocentro/distribuicoes/$id'
    | '/hemocentro/distribuicoes/planejar'
    | '/hemocentro/estoque/novo'
    | '/hemocentro/solicitacoes/$id'
    | '/hospital/solicitacoes/$id'
    | '/hospital/transportes/$id'
    | '/hemocentro/distribuicoes/'
    | '/hemocentro/estoque/'
    | '/hemocentro/solicitacoes/'
    | '/hospital/solicitacoes/'
    | '/hospital/transportes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AguardandoAprovacaoRoute: typeof AguardandoAprovacaoRoute
  CadastroRoute: typeof CadastroRoute
  HemocentroRoute: typeof HemocentroRouteWithChildren
  HospitalRoute: typeof HospitalRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aguardando-aprovacao': {
      id: '/aguardando-aprovacao'
      path: '/aguardando-aprovacao'
      fullPath: '/aguardando-aprovacao'
      preLoaderRoute: typeof AguardandoAprovacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hemocentro': {
      id: '/hemocentro'
      path: '/hemocentro'
      fullPath: '/hemocentro'
      preLoaderRoute: typeof HemocentroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital': {
      id: '/hospital'
      path: '/hospital'
      fullPath: '/hospital'
      preLoaderRoute: typeof HospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hemocentro/': {
      id: '/hemocentro/'
      path: '/'
      fullPath: '/hemocentro/'
      preLoaderRoute: typeof HemocentroIndexRouteImport
      parentRoute: typeof HemocentroRoute
    }
    '/hemocentro/indicadores': {
      id: '/hemocentro/indicadores'
      path: '/indicadores'
      fullPath: '/hemocentro/indicadores'
      preLoaderRoute: typeof HemocentroIndicadoresRouteImport
      parentRoute: typeof HemocentroRoute
    }
    '/hospital/': {
      id: '/hospital/'
      path: '/'
      fullPath: '/hospital/'
      preLoaderRoute: typeof HospitalIndexRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/nova-solicitacao': {
      id: '/hospital/nova-solicitacao'
      path: '/nova-solicitacao'
      fullPath: '/hospital/nova-solicitacao'
      preLoaderRoute: typeof HospitalNovaSolicitacaoRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hemocentro/distribuicoes/': {
      id: '/hemocentro/distribuicoes/'
      path: '/distribuicoes'
      fullPath: '/hemocentro/distribuicoes/'
      preLoaderRoute: typeof HemocentroDistribuicoesIndexRouteImport
      parentRoute: typeof HemocentroRoute
    }
    '/hemocentro/distribuicoes/$id': {
      id: '/hemocentro/distribuicoes/$id'
      path: '/distribuicoes/$id'
      fullPath: '/hemocentro/distribuicoes/$id'
      preLoaderRoute: typeof HemocentroDistribuicoesIdRouteImport
      parentRoute: typeof HemocentroRoute
    }
    '/hemocentro/distribuicoes/planejar': {
      id: '/hemocentro/distribuicoes/planejar'
      path: '/distribuicoes/planejar'
      fullPath: '/hemocentro/distribuicoes/planejar'
      preLoaderRoute: typeof HemocentroDistribuicoesPlanejarRouteImport
      parentRoute: typeof HemocentroRoute
    }
    '/hemocentro/estoque/': {
      id: '/hemocentro/estoque/'
      path: '/estoque'
      fullPath: '/hemocentro/estoque/'
      preLoaderRoute: typeof HemocentroEstoqueIndexRouteImport
      parentRoute: typeof HemocentroRoute
    }
    '/hemocentro/estoque/novo': {
      id: '/hemocentro/estoque/novo'
      path: '/estoque/novo'
      fullPath: '/hemocentro/estoque/novo'
      preLoaderRoute: typeof HemocentroEstoqueNovoRouteImport
      parentRoute: typeof HemocentroRoute
    }
    '/hemocentro/solicitacoes/': {
      id: '/hemocentro/solicitacoes/'
      path: '/solicitacoes'
      fullPath: '/hemocentro/solicitacoes/'
      preLoaderRoute: typeof HemocentroSolicitacoesIndexRouteImport
      parentRoute: typeof HemocentroRoute
    }
    '/hemocentro/solicitacoes/$id': {
      id: '/hemocentro/solicitacoes/$id'
      path: '/solicitacoes/$id'
      fullPath: '/hemocentro/solicitacoes/$id'
      preLoaderRoute: typeof HemocentroSolicitacoesIdRouteImport
      parentRoute: typeof HemocentroRoute
    }
    '/hospital/solicitacoes/': {
      id: '/hospital/solicitacoes/'
      path: '/solicitacoes'
      fullPath: '/hospital/solicitacoes/'
      preLoaderRoute: typeof HospitalSolicitacoesIndexRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/solicitacoes/$id': {
      id: '/hospital/solicitacoes/$id'
      path: '/solicitacoes/$id'
      fullPath: '/hospital/solicitacoes/$id'
      preLoaderRoute: typeof HospitalSolicitacoesIdRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/transportes/': {
      id: '/hospital/transportes/'
      path: '/transportes'
      fullPath: '/hospital/transportes/'
      preLoaderRoute: typeof HospitalTransportesIndexRouteImport
      parentRoute: typeof HospitalRoute
    }
    '/hospital/transportes/$id': {
      id: '/hospital/transportes/$id'
      path: '/transportes/$id'
      fullPath: '/hospital/transportes/$id'
      preLoaderRoute: typeof HospitalTransportesIdRouteImport
      parentRoute: typeof HospitalRoute
    }
  }
}

interface HemocentroRouteChildren {
  HemocentroIndicadoresRoute: typeof HemocentroIndicadoresRoute
  HemocentroIndexRoute: typeof HemocentroIndexRoute
  HemocentroDistribuicoesIdRoute: typeof HemocentroDistribuicoesIdRoute
  HemocentroDistribuicoesPlanejarRoute: typeof HemocentroDistribuicoesPlanejarRoute
  HemocentroEstoqueNovoRoute: typeof HemocentroEstoqueNovoRoute
  HemocentroSolicitacoesIdRoute: typeof HemocentroSolicitacoesIdRoute
  HemocentroDistribuicoesIndexRoute: typeof HemocentroDistribuicoesIndexRoute
  HemocentroEstoqueIndexRoute: typeof HemocentroEstoqueIndexRoute
  HemocentroSolicitacoesIndexRoute: typeof HemocentroSolicitacoesIndexRoute
}

const HemocentroRouteChildren: HemocentroRouteChildren = {
  HemocentroIndicadoresRoute: HemocentroIndicadoresRoute,
  HemocentroIndexRoute: HemocentroIndexRoute,
  HemocentroDistribuicoesIdRoute: HemocentroDistribuicoesIdRoute,
  HemocentroDistribuicoesPlanejarRoute: HemocentroDistribuicoesPlanejarRoute,
  HemocentroEstoqueNovoRoute: HemocentroEstoqueNovoRoute,
  HemocentroSolicitacoesIdRoute: HemocentroSolicitacoesIdRoute,
  HemocentroDistribuicoesIndexRoute: HemocentroDistribuicoesIndexRoute,
  HemocentroEstoqueIndexRoute: HemocentroEstoqueIndexRoute,
  HemocentroSolicitacoesIndexRoute: HemocentroSolicitacoesIndexRoute,
}

const HemocentroRouteWithChildren = HemocentroRoute._addFileChildren(
  HemocentroRouteChildren,
)

interface HospitalRouteChildren {
  HospitalNovaSolicitacaoRoute: typeof HospitalNovaSolicitacaoRoute
  HospitalIndexRoute: typeof HospitalIndexRoute
  HospitalSolicitacoesIdRoute: typeof HospitalSolicitacoesIdRoute
  HospitalTransportesIdRoute: typeof HospitalTransportesIdRoute
  HospitalSolicitacoesIndexRoute: typeof HospitalSolicitacoesIndexRoute
  HospitalTransportesIndexRoute: typeof HospitalTransportesIndexRoute
}

const HospitalRouteChildren: HospitalRouteChildren = {
  HospitalNovaSolicitacaoRoute: HospitalNovaSolicitacaoRoute,
  HospitalIndexRoute: HospitalIndexRoute,
  HospitalSolicitacoesIdRoute: HospitalSolicitacoesIdRoute,
  HospitalTransportesIdRoute: HospitalTransportesIdRoute,
  HospitalSolicitacoesIndexRoute: HospitalSolicitacoesIndexRoute,
  HospitalTransportesIndexRoute: HospitalTransportesIndexRoute,
}

const HospitalRouteWithChildren = HospitalRoute._addFileChildren(
  HospitalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AguardandoAprovacaoRoute: AguardandoAprovacaoRoute,
  CadastroRoute: CadastroRoute,
  HemocentroRoute: HemocentroRouteWithChildren,
  HospitalRoute: HospitalRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
