spring.application.name=backend

# Erros detalhados nas respostas da API
spring.mvc.problemdetails.enabled=true

# Logging para DEBUG (tirar no deploy)!
logging.level.org.springframework.web=DEBUG
# Debug micrometer
#logging.level.io.micrometer=DEBUG


# Banco H2 em arquivo
spring.datasource.url=jdbc:h2:file:./data/hemotrack-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Actuator + Micrometer -> OTLP
management.endpoints.web.exposure.include=health,metrics,info
management.metrics.tags.application=hemotrack-backend
# Grafana Cloud
management.otlp.metrics.export.enabled=${GRAFANA_OTLP_ENABLED:false}
management.otlp.metrics.export.url=${GRAFANA_OTLP_ENDPOINT:}
management.otlp.metrics.export.headers.Authorization=${GRAFANA_OTLP_TOKEN:}
management.otlp.metrics.export.step=10s